# Generated by Django 5.2.1 on 2025-06-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='SiteContactInfo',
        ),
    ]
