# Generated by Django 5.2.1 on 2025-06-11 15:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionvision',
            name='mission',
            field=ckeditor.fields.RichTextField(default='To be updated later'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionvision',
            name='vision',
            field=ckeditor.fields.RichTextField(default='To be updated later'),
            preserve_default=False,
        ),
    ]
