# Generated by Django 5.2.1 on 2025-06-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_missionvision_mission_missionvision_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='courses/'),
            preserve_default=False,
        ),
    ]
