# Generated by Django 5.2.1 on 2025-06-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('duration_weeks', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('image', models.ImageField(upload_to='courses/')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_certified', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, choices=[('bestseller', 'Bestseller'), ('new', 'New'), ('popular', 'Popular'), ('job_ready', 'Job Ready'), ('limited', 'Limited Seats')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecategory')),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
    ]
